### ISSUE TITLE
Edit this page on Github link

### ISSUE THREAD

**Issue by techtonik** [GrahamDumpleton/wsgiorg#27]
It will greatly help to add "Edit the page in Github" links. The list of software definitely need updating.

Does wsgi.org hosted on read-the-docs?
- http://mg.pov.lt/blog/sphinx-edit-on-github

If not, perhaps this will help:
- http://mg.pov.lt/blog/sphinx-edit-on-github
- http://blog.nikhilism.com/2012/08/automatic-github-pages-generation-from.html

**Comment by masklinn** [comment]
Fixed by the migration to RTD.
