### ISSUE TITLE
Some external links in the documentation site are outdated

### ISSUE THREAD

**Issue by kinlearn** [GrahamDumpleton/wsgiorg#50]
Hi! Some of the external links in the [documentation page](https://wsgi.readthedocs.io/en/latest/learn.html) need to be updated. Please check the pull request.
(I'm new to open source. This is my first attempt of contribution.)

**Comment by masklinn** [comment]
Heya, thanks for the contribution (probably). If you're opening a PR it's probably not necessary to open an issue with the same content. Opening an issue (or a discussion thread when they're active) can be useful to discuss things before opening a PR.

**Comment by kinlearn** [comment]
Thanks @masklinn! 
I didn't know this.. will remember this!
Thank you so much again! 🙌
